import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/common/NavBar";
import RevealAnimation from "@/components/common/RevealAnimation";
import SmoothScrolling from "@/components/common/SmoothScrolling";
import { Suspense } from "react";
import IntroLoader from "@/components/common/IntroLoader2";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ananta",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        cz-shortcut-listen="true"
      > 
        <IntroLoader />
        <Suspense fallback={null}>
          <SmoothScrolling />
        </Suspense>
        {/* <RevealAnimation /> */}
        <NavBar />
        {children}
      </body>
    </html>
  );
}
